name: hadir

packages:
  - packages/**
  - apps/**

scripts:
  analyze:
    exec: dart analyze .
  
  format:
    exec: dart format .

  refresh:
    exec: flutter clean && flutter clean cache && flutter pub get