name: hadir_ui_desktop
description: Desktop UI package for Hadir attendance system
version: 0.0.1

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  fluent_ui: ^4.9.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  go_router: ^14.6.2
  hadir_core: ^0.0.1
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  system_theme: ^3.1.2
  window_manager: ^0.4.3

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  very_good_analysis: ^6.0.0
