name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    
    - name: Install Melos
      run: dart pub global activate melos
    
    - name: Get Dependencies
      run: melos bootstrap
    
    - name: Analyze
      run: melos run analyze
    
    - name: Format
      run: melos run format